# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2aab5f5f2f23c6b864319dce2f79f04996d36dba2cf20a438504d22d0db4c94db92b084f67f8543894e5c48ed68de6c751a09d67f3ec3d51c5c59101cdf72b4

test:
  secret_key_base: ae3be5539c5caace618319f264057e46acba5d57d631831bba6d003322eedd8ff92c02f45acd0118aeeea03ae522fc4f0c231354a7de2e638cb34437c1e410cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
